### PR TITLE
keep origin state from getInitialState and componentDidMount

### PR DESCRIPTION
**Pull request by yaliyingwy**

### CODE REVIEW

**Comment by kyldvs** [comment]
Thanks for the PR,

1. There is no need to update lib/dist files in the PR. We do that in one big batch when we make a release every once in a while. Please just submit the small change you are making, https://github.com/yaliyingwy/flux/commit/e81e73cfca9808db59bedc8ddbb04cb24057d26a

2. Can you provide more context in your description so that we can understand why this change is necessary? A code example of something that breaks would be helpful.

**Comment by yaliyingwy** [comment]
class Foo extends Component {
  constructor() {
    super();
    this.displayName = 'Foo';
    this.state = {
      bar: 'some value',
    };
  }
  render() {
    const { bar } = this.state;  //bar is undefine in the first render, becase container rewrite the state after componentDidMount.
  }
}

**Comment by yaliyingwy** [comment]
Sometimes I don't want to put all states in the stores, like form in the login page,  I just bind the input values on the component state, but now I cant find a way to set the component initial state, container will rewrite my state after componentDidMount.

**Comment by kyldvs** [comment]
I think mixing component state with store state in a single component is a bad pattern. A container's only responsibility should be connecting state from a store to a view. So I would rewrite the above as:

```
class FooView extends Component {
  static propTypes = {
    stateInStore: PropTypes.string,
  }

  constructor(props) {
    super(props);
    this.state = { bar: 'some value' };
  }

  render() {
    const bar = this.state.bar;
    const stateInStore = this.props.stateInStore;
    // render something
  }
}

class FooContainer extends Component {
  static getStores() {
    return [FooStore];
  }

  static calculateState() {
    return {
      stateInStore: FooStore.getState().get('stateInStore');
    }
  }

  render() {
    return <FooView {...this.state} />;
  }
}
```

**Comment by yaliyingwy** [comment]
Thank you,  I will try this in my code.
 @kyldvs ,Is this also the right way to resole  [https://github.com/facebook/flux/issues/316](https://github.com/facebook/flux/issues/316)? In FooView's `componentDidMount`, call an action to change state in the store.

**Comment by kyldvs** [comment]
I think that is a different issue, there is a small period of time through the mounting process that can cause changes to be ignored by a container.

**Pull request closed without merging**
