### PR TITLE
Refactored current website in Docusaurus

### PR DESCRIPTION
**Pull request by micheleriva**
Hi @kyldvs ,
I refactored the entire website with Docusaurus due to your comment in the #434 PR:

> If anyone has the time to upgrade the site infrastructure I'd love to support them. If not the site will probably remain in its current state.

I love flux, I learned so much thanks to Facebook Opensource, so I decided to dedicate some time to upgrade the documentation for the architecture that changed forever my way of thinking about JavaScript web applications.

I would love to help more 😄 
Best regards

### CODE REVIEW

**Comment by micheleriva** [comment]
I'll attach here some screenshot of the new Docusaurus website proposal:

schermata 2019-01-04 alle 16 34 11
schermata 2019-01-04 alle 16 34 23
schermata 2019-01-04 alle 16 34 27
schermata 2019-01-04 alle 16 34 31

**Comment by kyldvs** [comment]
This is great! I will take a look at this after I get back from holidays. Excited for the site to be cleaned up

**Comment by kyldvs** [comment]
This looks good to me - I'll go ahead and merge this in and will mess around with figuring out how to publish this to the actual site.

Thanks for working on this!

**Comment by micheleriva** [comment]
@kyldvs I'd love to help to maintain this website, if you need some change please ping me 😄

**Comment by micheleriva** [comment]
Hey @kyldvs let me know if I can help someway!
I'd love to help maintaining this project 😄

**Comment by yangshun** [comment]
Feel free to let me know if we (Docusaurus team) can help in any way, very glad to see Flux moving to Docusaurus! 😄

cc @JoelMarcey

**Pull request merged**
