### PR TITLE
Flux Chat: ES6, Reduce Stores, Containers and ImmutableJS

### PR DESCRIPTION
**Pull request by alexeyraspopov**
Flux Chat example is old and does not use good things like Flux Utils or ImmutableJS. Let's fix this.

This Flux Chat wrote from scratch, so here is a list of things that are changed:
- Used `immutable` lib for all data (messages, threads). `MessageRecord` and `ThreadRecord` are introduced to provide the shape of data. I did not consider using Flow (see #365).
- Better files structure: top level folders `core`, `message`, `thread` which contain related components/stores/records.
- ES2015 everywhere.
- `ReduceStore` and `Container` are used.
- `MessageBufferStore` holds incomplete messages per threads.
- Example chat data was moved to JSON file.

Next pull requests are included here or becoming outdated:
- #312: becomes irrelevant
- #324, #337: included here
- #323: `package.json` updated
- #321: included here
- #307: becomes irrelevant
- #291: changes to `ThreadStore` are included here
- #250: can be updated if this will be merged
- #236: becomes irrelevant

_Note: GIT has some weird definition of showing diff, it's much easier to review by pulling the branch and checking new files._

cc @kyldvs @fisherwebdev

### CODE REVIEW

**Comment by alexeyraspopov** [comment]
@kyldvs, Flux tests are failing on Travis, probably, because of Jest version. I can open separate PR with changes to `package.json` if needed.

**Comment by alexeyraspopov** [comment]
@kyldvs, any chances to have this reviewed? I can write better description of particular changes if you need.

**Comment by alexeyraspopov** [comment]
@kyldvs, I've updated folders structure.

**Comment by alexeyraspopov** [comment]
@kyldvs, any chance for this to be merged?

**Comment by alexeyraspopov** [comment]
Oh boy

Gonna resolve conflicts in the morning. Stay tuned.

**Comment by kyldvs** [comment]
Hey @alexeyraspopov, before doing to much work on this we should chat about what this example explains that the others do not cover. I'm certainly open to adding more examples but do not want to add examples that are just re-hashing what others already cover. That will just lead to a lot more maintenance cost without much benefit.

Could you run through how it's different from https://github.com/facebook/flux/tree/master/examples/flux-async for example.

**Comment by alexeyraspopov** [comment]
Oh it was an amazing year :)

@kyldvs, the main point of this PR was to refresh the chat example, with newer tools, ES6, and more important Flux Utils. Since the chat example is mostly the first thing the developer reads, it is important to show the best way to work with Flux (using Dispatcher and ReduceStore).

**Pull request closed without merging**
