### PR TITLE
Update react, withProps coverage, context api migration

### PR DESCRIPTION
**Pull request by tomtwttr**
This diff:

1) Updates react
```
yarn add react
yarn add react-dom
yarn add react-addons-test-utils
```
2) Adds code coverage to `componentWillReceiveProps` of FluxContainer. This is necessary before proper fix for `UNSAFE_componentWillReceiveProps` can be implemented. This relates to #452 .

3) Updates to migrate to new `Context` API

### CODE REVIEW

**Comment by waka** [comment]
This is the pull request with hope!

**Comment by tomtwttr** [comment]
Hey @kyldvs , are you able to review?

**Comment by kyldvs** [comment]
Hey @tomtwttr, thanks for the PR! Sorry for the delay, I was holding off because it looked like a draft PR for a while :)

This looks good to me. Before I merge I will just need to make sure these changes don't cause any problems in our internal repos. This is because we like to have code on facebook org reflect what we are actually using in production, so I wouldn't want it to diverge too much. I will update you once I've pulled this in and checked.

**Comment by tomtwttr** [comment]
Thanks @kyldvs , apologies for the draft mode, was waiting for that "CLA Signed" process to go through. I look forward to hearing your results.

**Comment by kyldvs** [comment]
Looks good :) thanks!

**Comment by tomtwttr** [comment]
@kyldvs What's the process for an NPM version bump?

**Comment by waka** [comment]
Isn't the version with this pull request published on npm?

**Comment by tomtwttr** [comment]
@kyldvs Would you be able to bump npm?

Screen Shot 2020-03-26 at 8 50 58 AM

**Comment by waka** [comment]
@kyldvs @mariobanks Is this library no longer pushed to npm?

**Pull request merged**
