### PR TITLE
fix: Container.create doesn't work with Babel v7.10

### PR DESCRIPTION
**Pull request by koba04**
As #486 #489 mentioned, `Container.create` does not work with Babel v7.10.
To fix this, I've updated the version of Babel to the latest version.
I've also updated `fbjs` and used `babel-preset-fbjs` instead of `fbjs-scripts` because I have to use `stripDev` option.

I'm not familiar with `fbjs` and a module system that facebook uses, so please correct me if I misunderstand.

This version still seems not to work with a project based on `cra`, so I'll investigate it. 
> "cannot be invoked without 'new'"

I've published this version as a forked package `@koba04/flux`, so you can test the build with the package.

### CODE REVIEW

**Comment by kyldvs** [comment]
Thanks for working on this! @yangshun or I can help with a release when this is ready to go

**Comment by rvignacio** [comment]
I tested this PR in the context of my previously failing project and it works with latest Babel version (#489).

**Comment by koba04** [comment]
@rvignacio Thank you for testing this!

**Comment by Bloomca** [comment]
@koba04 I tested your package (`@koba04/flux`) in our project and it also works with the latest Babel version.

**Comment by koba04** [comment]
@Bloomca Thank you for testing this!
This seems to work fine with the latest version of Babel.

**Comment by koba04** [comment]
@kyldvs Could you review this?

**Comment by yangshun** [comment]
Thanks a lot @koba04! I'll merge first and resolve some of the conflicts. We aim to release a v4.0.0 this week.

**Comment by koba04** [comment]
@yangshun Thank you for merging this! Please let me know If there is any problem. I'll work on this.

**Comment by yangshun** [comment]
@koba04 We've released v4.0.0! Would appreciate if you could help to test it 😄

**Pull request merged**
