### PR TITLE
correct video.html next link button href

### PR DESCRIPTION
**Pull request by huang-x-h**

### CODE REVIEW

**Comment by johnantoni** [comment]
ready to merge ?

**Comment by kyldvs** [comment]
I'm not confident this is the correct fix. I have very limited knowledge of how the site is actually built. I believe the next time we generate the site this link would get broken again.

If someone wanted to help upgrade the site infrastructure to something like https://docusaurus.io/ that would be amazing.

**Comment by huang-x-h** [comment]
@kyldvs yes, it's incorrect, forgot the site is compiled.

If we want to fix it, we should add extra option in `docs/Videos.md` metadata to indicate

eg:

```
---
id: videos
title: Videos
layout: docs
category: Resources
permalink: docs/videos.html
next: react
nextExternalUrl: true // tell Docslayout next page is a external url not a content url
---
```

If upgrade the site infrastructure to `Docusaurus`, it will change a lot of things.

**Comment by kyldvs** [comment]
Yeah it would change a lot. The last three times I've upgraded the site with the X year olds scripts I've completely broken it. I'm _very_ hesitant to push any updates unless there is something major that needs to get in.

If anyone has the time to upgrade the site infrastructure I'd love to support them. If not the site will probably remain in its current state.

**Comment by micheleriva** [comment]
Hi @kyldvs ,
I'd love to upgrade the current site infrastructure to Docusaurus! How should I proceed? Should I fork and then create a custom branch?

**Comment by micheleriva** [comment]
I'll attach here some screenshot of the new Docusaurus website:
schermata 2019-01-04 alle 16 34 11
schermata 2019-01-04 alle 16 34 23
schermata 2019-01-04 alle 16 34 27
schermata 2019-01-04 alle 16 34 31

**Comment by kyldvs** [comment]
Going to close this in favor of #466

**Pull request closed without merging**
