### PR TITLE
Fix deprecated flow syntax

### PR DESCRIPTION
**Pull request by alexeyraspopov**
Based on https://github.com/facebook/flow/issues/1284 and https://github.com/facebook/flow/issues/1215

### CODE REVIEW

**Comment by kyldvs** [comment]
Thanks!

**Comment by alexeyraspopov** [comment]
@kyldvs thank you! When can we expect new release version? So this and updated version of fbjs will be available for NPM users.

**Comment by kyldvs** [comment]
We can probably do a version bump. Could you clarify for me why it's necessary though? I don't think anything will have changed since the last version. (I'm mostly unfamiliar with the beast that is npm)

**Comment by alexeyraspopov** [comment]
At least it will allow users to use Flux (including Flux utils) with Flow :)

**Comment by kyldvs** [comment]
Ah yeah, we have a few issues we need to resolve to make Flux utils usable with flow. Particularly #297 and #304. After those we should definitely bump the version.

**Pull request merged**
