### PR TITLE
Korean translation for Docs

### PR DESCRIPTION
**Pull request by haruair**
This PR is related #141. The PR is included Korean Translation of all Flux documentation.

And also I've found some trouble with `DocsSidebar` cause of translation documents.

`metadata.js` is automatically created all of the documents. That makes an issue with `DocsSidebar`.
`DocsSidebar` gets all metadata and finds a head of the tree, However, there is two head exists because of multi-language documents. Thus I added the code c707915da0f9c5ffc230e1e7b880abbb36811797 what quick look up the lang property from the documents. However, I'm still not sure with this dirty solution for i18n.

I'm looking forward to feedback. Let me know if you have any suggestions or recommendations.

### CODE REVIEW

**Comment by fisherwebdev** [comment]
Thanks for this!  

@vjeux or @zpao you might want to take a look at the change here: https://github.com/facebook/flux/pull/199/files#diff-11 Also, does this look similar to how we've done translations in the past?

**Comment by zzz6519003** [comment]
hey Kobe XD

**Comment by dalinaum** [comment]
Is there any update on this issue?

**Comment by zpao** [comment]
@fisherwebdev - seems fine. We haven't done any translations for the react-page based docs (AFAIK). React docs use jekyll and the solution is pretty similar. The result is the same in that the only docs linked are en-US but the translations are available if you go to the right link. One day we'll converge on something that works smoothly.

**Comment by fisherwebdev** [comment]
ok great!  thanks all, especially @haruair.

**Pull request merged**
