### PR TITLE
refine demo code

### PR DESCRIPTION
**Pull request by hunter2009**
Refine code to fix bug that message id is not same as which store in localStorage.

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by hunter2009** [comment]
@facebook-github-bot-8 Got it.

**Comment by hunter2009** [comment]
Pls refine it . @kyldvs

**Comment by facebook-github-bot-3** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by kyldvs** [comment]
Thanks for the PR, we recently updated the examples so this is no longer relevant.

https://github.com/facebook/flux/tree/master/examples

**Pull request closed without merging**
