### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by kkirsche** [comment]
Signed

**Comment by kyldvs** [comment]
I think version is helpful documentation even if bower doesn't necessarily need it

**Comment by kkirsche** [comment]
To each their own. I strongly disagree with you.

**Comment by kyldvs** [comment]
Not familiar with bower so feel free to teach me something. Is it easy to see what version of flux you will be using from bower if this version key is not there?

**Comment by zpao** [comment]
Bower will use git tags and tell you what version you installed when it installs. We should just do what is common practice / spec.

We should also probably be adding a header to our dist files that includes copyright and version information, then there's always that to look at if you don't know what version you have installed.

**Comment by zpao** [comment]
Though maybe it's not so useless as VS still uses it: https://github.com/reactjs/react-bower/issues/17

**Comment by kyldvs** [comment]
Hmm, if there are plans to merge that into react I guess we should keep version too. If not I'm happy to remove it.

**Pull request closed without merging**
